In [22]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
df_2004 = pd.read_csv('Processed_loans_2004.csv')
df_2008 = pd.read_csv('Processed_loans_2008.csv')
df_2012 = pd.read_csv('Processed_loans_2012.csv')
df_2016 = pd.read_csv('Processed_loans_2016.csv')

In [12]:
# df_ml = df[df.Current_Status != 'Current']
df_ml_2004 =df_2004
df_target_2004 = df_ml_2004.Current_Status

df_ml_2004 = df_ml_2004.drop('Current_Status',axis=1)
df_ml_2004.drop(['Loan_ID','Origination_Date','First_Payment_Date','CLTV','State','Zip','Product','Period','Zero_Bal_Cd','Origin_Month','Origin_Year'],axis=1,inplace= True)
cleanup_nums = {"Term_bins":     {"<= 30 Years": 1, "<=15 Years": 0},
                "FICO_bins": {"0-620": 0, "620-660": 1, "660-700": 2, "700-740": 3,
                                  "740-780": 4, "780+": 5 }}
df_ml_2004.replace(cleanup_nums, inplace=True)
df_ml_2004 = pd.get_dummies(df_ml_2004)
df_ml_2004.shape

(100000, 54)

In [13]:
# df_ml = df[df.Current_Status != 'Current']
df_ml_2008 =df_2008
df_target_2008 = df_ml_2008.Current_Status

df_ml_2008 = df_ml_2008.drop('Current_Status',axis=1)
df_ml_2008.drop(['Loan_ID','Origination_Date','First_Payment_Date','CLTV','State','Zip','Product','Period','Zero_Bal_Cd','Origin_Month','Origin_Year'],axis=1,inplace= True)
cleanup_nums = {"Term_bins":     {"<= 30 Years": 1, "<=15 Years": 0},
                "FICO_bins": {"0-620": 0, "620-660": 1, "660-700": 2, "700-740": 3,
                                  "740-780": 4, "780+": 5 }}
df_ml_2008.replace(cleanup_nums, inplace=True)
df_ml_2008 = pd.get_dummies(df_ml_2008)
df_ml_2008.shape

(100000, 53)

In [14]:
# df_ml = df[df.Current_Status != 'Current']
df_ml_2012 =df_2012
df_target_2012 = df_ml_2012.Current_Status

df_ml_2012 = df_ml_2012.drop('Current_Status',axis=1)
df_ml_2012.drop(['Loan_ID','Origination_Date','First_Payment_Date','CLTV','State','Zip','Product','Period','Zero_Bal_Cd','Origin_Month','Origin_Year'],axis=1,inplace= True)
cleanup_nums = {"Term_bins":     {"<= 30 Years": 1, "<=15 Years": 0},
                "FICO_bins": {"0-620": 0, "620-660": 1, "660-700": 2, "700-740": 3,
                                  "740-780": 4, "780+": 5 }}
df_ml_2012.replace(cleanup_nums, inplace=True)
df_ml_2012 = pd.get_dummies(df_ml_2012)
df_ml_2012.shape

(100000, 55)

In [15]:
# df_ml = df[df.Current_Status != 'Current']
df_ml_2016 =df_2016
df_target_2016 = df_ml_2016.Current_Status

df_ml_2016 = df_ml_2016.drop('Current_Status',axis=1)
df_ml_2016.drop(['Loan_ID','Origination_Date','First_Payment_Date','CLTV','State','Zip','Product','Period','Zero_Bal_Cd','Origin_Month','Origin_Year'],axis=1,inplace= True)
cleanup_nums = {"Term_bins":     {"<= 30 Years": 1, "<=15 Years": 0},
                "FICO_bins": {"0-620": 0, "620-660": 1, "660-700": 2, "700-740": 3,
                                  "740-780": 4, "780+": 5 }}
df_ml_2016.replace(cleanup_nums, inplace=True)
df_ml_2016 = pd.get_dummies(df_ml_2016)
df_ml_2016.shape

(100000, 56)

In [17]:
print(df_target_2004.value_counts())
print(df_target_2008.value_counts())
print(df_target_2012.value_counts())
print(df_target_2016.value_counts())

Prepaid            90026
Current             6556
Underperforming     3418
Name: Current_Status, dtype: int64
Prepaid            87017
Current             7212
Underperforming     5771
Name: Current_Status, dtype: int64
Current            53775
Prepaid            46070
Underperforming      155
Name: Current_Status, dtype: int64
Current            82548
Prepaid            17352
Underperforming      100
Name: Current_Status, dtype: int64


# Modelling with all features 2004


In [18]:
df_ml_org =df_2004

In [19]:
df_ml_org = df_2004[df_2004['Current_Status'] != 'Current']

In [20]:
df_ml = df_ml_org.drop(['Loan_ID','Origination_Date','First_Payment_Date','CLTV','Zip','Product','Period','Zero_Bal_Cd','Origin_Month','Origin_Year'],axis=1)#,inplace= True)
df_target = df_ml.Current_Status
df_ml = df_ml.drop('Current_Status',axis=1)
cleanup_nums = {"Term_bins":     {"<= 30 Years": 1, "<=15 Years": 0},
                "FICO_bins": {"0-620": 0, "620-660": 1, "660-700": 2, "700-740": 3,
                                  "740-780": 4, "780+": 5 }}
df_ml = df_ml.replace(cleanup_nums)#, inplace=True)
df_ml = pd.get_dummies(df_ml)

# Spliting Data for train and Test

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# split data into train and test set
x_train, x_test, y_train, y_test = train_test_split(df_ml, df_target, random_state=0)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Decision Tree

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# Decision tree
clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [25]:
accuracy_score(y_test, y_pred)

0.9408843799494885

In [26]:
confusion_matrix(y_test, y_pred)

array([[21770,   721],
       [  660,   210]], dtype=int64)

In [27]:
feature_val = pd.DataFrame(clf.feature_importances_)
columns = pd.DataFrame(df_ml.columns)
feature = pd.concat([columns, feature_val], axis =1)
feature.columns = ['Feature_DT', 'DT_2004']

In [29]:
# feature

# Modelling with all features 2008


In [30]:
df_ml_org =df_2008

In [31]:
df_ml_org = df_2008[df_2008['Current_Status'] != 'Current']

In [32]:
df_ml = df_ml_org.drop(['Loan_ID','Origination_Date','First_Payment_Date','CLTV','Zip','Product','Period','Zero_Bal_Cd','Origin_Month','Origin_Year'],axis=1)#,inplace= True)
df_target = df_ml.Current_Status
df_ml = df_ml.drop('Current_Status',axis=1)
cleanup_nums = {"Term_bins":     {"<= 30 Years": 1, "<=15 Years": 0},
                "FICO_bins": {"0-620": 0, "620-660": 1, "660-700": 2, "700-740": 3,
                                  "740-780": 4, "780+": 5 }}
df_ml = df_ml.replace(cleanup_nums)#, inplace=True)
df_ml = pd.get_dummies(df_ml)

# Spliting Data for train and Test

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# split data into train and test set
x_train, x_test, y_train, y_test = train_test_split(df_ml, df_target, random_state=0)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# Decision tree
clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [35]:
accuracy_score(y_test, y_pred)

0.9415692821368948

In [36]:
confusion_matrix(y_test, y_pred)

array([[21793,   698],
       [  667,   203]], dtype=int64)

In [38]:
feature_val = pd.DataFrame(clf.feature_importances_)
feature['Feature_DT_2008'] = pd.DataFrame(df_ml.columns)
feature['DT_2008'] = feature_val

In [40]:
# feature

# Modelling with all features 2012


In [41]:
df_ml_org = df_2012[df_2012['Current_Status'] != 'Current']

In [42]:
df_ml = df_ml_org.drop(['Loan_ID','Origination_Date','First_Payment_Date','CLTV','Zip','Product','Period','Zero_Bal_Cd','Origin_Month','Origin_Year'],axis=1)#,inplace= True)
df_target = df_ml.Current_Status
df_ml = df_ml.drop('Current_Status',axis=1)
cleanup_nums = {"Term_bins":     {"<= 30 Years": 1, "<=15 Years": 0},
                "FICO_bins": {"0-620": 0, "620-660": 1, "660-700": 2, "700-740": 3,
                                  "740-780": 4, "780+": 5 }}
df_ml = df_ml.replace(cleanup_nums)#, inplace=True)
df_ml = pd.get_dummies(df_ml)

# Spliting Data for train and Test

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# split data into train and test set
x_train, x_test, y_train, y_test = train_test_split(df_ml, df_target, random_state=0)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Decision Tree

In [44]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# Decision tree
clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [45]:
accuracy_score(y_test, y_pred)

0.9929047330622134

In [46]:
confusion_matrix(y_test, y_pred)

array([[11471,    47],
       [   35,     4]], dtype=int64)

In [47]:
feature_val = pd.DataFrame(clf.feature_importances_)
feature['Feature_DT_2012'] = pd.DataFrame(df_ml.columns)
feature['DT_2012'] = feature_val

In [61]:
feature

Feature_DT   DT_2004  \
0                                        Interest_Rate  0.039789   
1                                                  UPB  0.089496   
2                                            Loan_Term  0.006806   
3                                                  LTV  0.055532   
4                                        Num_Borrowers  0.014403   
5                                                  DTI  0.071546   
6                                        Borrower_FICO  0.095951   
7                                           Unit_Count  0.006164   
8                                           Insurance%  0.010849   
9                              Mortgage_Insurance_Type  0.002037   
10                                          Current_IR  0.033895   
11                                         Current_UPB  0.095229   
12                                                 Age  0.104574   
13                                           FICO_bins  0.006842   
14                                           Term_bins  0.002134   
15                                           Channel_B  0.011176   
16                                           Channel_C  0.009692   
17                                           Channel_R  0.009612   
18                                 Seller_AMTRUST BANK  0.006470   
19                        Seller_BANK OF AMERICA, N.A.  0.011301   
20      Seller_BISHOPS GATE RESIDENTIAL MORTGAGE TRUST  0.000522   
21                           Seller_CITIMORTGAGE, INC.  0.005891   
22    Seller_FIRST TENNESSEE BANK NATIONAL ASSOCIATION  0.001269   
23                           Seller_FLAGSTAR BANK, FSB  0.006799   
24                           Seller_GMAC MORTGAGE, LLC  0.005118   
25                Seller_HARWOOD STREET FUNDING I, LLC  0.002121   
26                  Seller_IRWIN MORTGAGE, CORPORATION  0.002081   
27                      Seller_JPMORGAN CHASE BANK, NA  0.004113   
28                                        Seller_OTHER  0.009299   
29   Seller_PRINCIPAL RESIDENTIAL MORTGAGE CAPITAL ...  0.003428   
..                                                 ...       ...   
78                                            State_NC  0.002054   
79                                            State_ND  0.000000   
80                                            State_NE  0.000415   
81                                            State_NH  0.002579   
82                                            State_NJ  0.002804   
83                                            State_NM  0.000873   
84                                            State_NV  0.006253   
85                                            State_NY  0.003084   
86                                            State_OH  0.006200   
87                                            State_OK  0.000946   
88                                            State_OR  0.000666   
89                                            State_PA  0.004802   
90                                            State_PR  0.001504   
91                                            State_RI  0.001049   
92                                            State_SC  0.001827   
93                                            State_SD  0.000336   
94                                            State_TN  0.002979   
95                                            State_TX  0.002781   
96                                            State_UT  0.000357   
97                                            State_VA  0.002036   
98                                            State_VI  0.000000   
99                                            State_VT  0.000355   
100                                           State_WA  0.002013   
101                                           State_WI  0.005664   
102                                           State_WV  0.001254   
103                                           State_WY  0.000000   
104                             Relocation_Indicator_N  0.000000   
105                             

# Modelling with all features 2016


In [50]:
df_ml_org = df_2016[df_2016['Current_Status'] != 'Current']

In [51]:
df_ml = df_ml_org.drop(['Loan_ID','Origination_Date','First_Payment_Date','CLTV','Zip','Product','Period','Zero_Bal_Cd','Origin_Month','Origin_Year'],axis=1)#,inplace= True)
df_target = df_ml.Current_Status
df_ml = df_ml.drop('Current_Status',axis=1)
cleanup_nums = {"Term_bins":     {"<= 30 Years": 1, "<=15 Years": 0},
                "FICO_bins": {"0-620": 0, "620-660": 1, "660-700": 2, "700-740": 3,
                                  "740-780": 4, "780+": 5 }}
df_ml = df_ml.replace(cleanup_nums)#, inplace=True)
df_ml = pd.get_dummies(df_ml)

# Spliting Data for train and Test

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# split data into train and test set
x_train, x_test, y_train, y_test = train_test_split(df_ml, df_target, random_state=0)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Decision Tree

In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# Decision tree
clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [54]:
accuracy_score(y_test, y_pred)

0.9867063946825578

In [55]:
confusion_matrix(y_test, y_pred)

array([[4305,   32],
       [  26,    0]], dtype=int64)

In [56]:
feature_val = pd.DataFrame(clf.feature_importances_)
feature['Feature_DT_2016'] = pd.DataFrame(df_ml.columns)
feature['DT_2016'] = feature_val

In [59]:
feature

In [62]:
# feature.to_csv("features.csv")